### ISSUE TITLE
Add PyPI maintainers from DAMA to suitcase-*

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/suitcase-utils#18]
We need to be able to push new releases of the software to PyPI. Here is one example of a blocking issue due to this: https://github.com/NSLS-II/suitcase-tiff/pull/23#issuecomment-475685371.

**Comment by danielballan** [comment]
Apologies for the accidental gate-keeping! Not good!

I systematically went through and added @stuartcampbell, @mrakitin, and @tacaswell and co-owners on all packages where I was previously the sole owner. The PyPI UI helpfully highlights packages where the logged-in user is the sole owner like so:

![image](https://user-images.githubusercontent.com/2279598/54880254-3f9e5200-4e19-11e9-9fe5-e389a3347a6a.png)

so it was easy to verify that I am no longer the sole owner of any DAMA projects.

That's the short-term solution. In the long term, since there are going to be many suitcase packages to manage, we should consider making a PyPI deploy account and using Travis to automate PyPI deployments, rather than adding/removing co-owners from N projects as people join/leave DAMA.

**Comment by mrakitin** [comment]
Thanks @danielballan! I think it resolves the issue.
